spring:
  datasource:
    url: jdbc:postgresql://usercredentials.c2ndtqgogv2h.us-east-2.rds.amazonaws.com:5432/usercredentials
    driver-class-name: org.postgresql.Driver
    username: 'yassine'
    password: 'MedYassine00'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 743677397A244326452948404D635166546A576E5A7234753778214125442A47

server:
  port: 8081